// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZMb3eG6q7G11QlVdkg1N4sPUH2UW6CQ',
    appId: '1:197524813017:web:1bdd8031c2eb9a868c3ac8',
    messagingSenderId: '197524813017',
    projectId: 'reminder-app-51a38',
    authDomain: 'reminder-app-51a38.firebaseapp.com',
    storageBucket: 'reminder-app-51a38.firebasestorage.app',
    measurementId: 'G-935864J494',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2YatRWApTyUoSZ9-GTzpGDFPD0AgfQU',
    appId: '1:197524813017:android:614b55aacfd89fd38c3ac8',
    messagingSenderId: '197524813017',
    projectId: 'reminder-app-51a38',
    storageBucket: 'reminder-app-51a38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMhi3gMDeezO8wPVGDHc8DdTzErwV7r8',
    appId: '1:197524813017:ios:6fffa4ff2b4900988c3ac8',
    messagingSenderId: '197524813017',
    projectId: 'reminder-app-51a38',
    storageBucket: 'reminder-app-51a38.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpZMb3eG6q7G11QlVdkg1N4sPUH2UW6CQ',
    appId: '1:197524813017:web:131c4c4a9b7cd1258c3ac8',
    messagingSenderId: '197524813017',
    projectId: 'reminder-app-51a38',
    authDomain: 'reminder-app-51a38.firebaseapp.com',
    storageBucket: 'reminder-app-51a38.firebasestorage.app',
    measurementId: 'G-XSDWE991NP',
  );
}
